language: python
before_script:
 - echo "Starting build"
script:
 - python setup.py test
 - bash pycodestyle.sh
after_script:
 - echo "Script finished"
after_success:
 - echo "Build was successful. $TRAVIS_TEST_RESULT"
after_failure:
 - echo "Build was failed"
