language: python
before_script:
 - echo "Starting build"
script:
 - python setup.py test
 - pip install pycodestyle
 - pycodestyle --first --ignore=E501,E722,E704
after_script:
 - echo "Script finished"
after_success:
 - echo "Build was successful. $TRAVIS_TEST_RESULT"
after_failure:
 - echo "Build was failed"
