language: python
before_script:
 - echo "Starting build"
script:
 - python setup.py test
after_script:
 - echo "Script finished"
 - echo pycodestyle 
 - bash pycodestyle.sh
 - pycodestyle --first 
after_success:
 - echo "Build was successful. $TRAVIS_TEST_RESULT"
after_failure:
 - echo "Build was failed"
